name: ✨ 기능 기획
description: 새로운 기능을 정의하고 구현 계획을 세웁니다.
title: "[Feature] "
labels: [feature, planning]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능을 기획하고 구현 계획을 세워보세요.  
        이 이슈는 개발 전에 기능을 명확히 정의하고, 필요한 컴포넌트를 정리하는 데 사용됩니다.
  - type: input
    id: feature-name
    attributes:
      label: 기능 이름
      description: 기능을 한 줄로 요약해주세요.
      placeholder: "예: 사용자 회원가입 API"
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 어떤 기능인지, 왜 필요한지 설명해주세요.
      placeholder: "예: 사용자가 이메일과 비밀번호로 회원가입할 수 있도록 한다."
  - type: textarea
    id: requirements
    attributes:
      label: 구현에 필요한 요소
      description: 필요한 클래스, 메서드, API 엔드포인트 등을 정리해주세요.
      placeholder: "- UserController에 POST /signup 추가\n- UserService에 createUser 메서드 구현\n- User 엔티티에 validation 로직 추가\n- 테스트 코드 작성 (단위/통합)"
  - type: textarea
    id: considerations
    attributes:
      label: 고려 사항
      description: 보안, 예외 처리, 성능 등 특별히 고려해야 할 점이 있다면 적어주세요.
      placeholder: "예: 비밀번호는 해시 처리해야 하며, 중복 이메일은 예외 처리 필요"
